<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenDemo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>e15a2d76-a278-42aa-bf78-e18700f45fa9</testSuiteGuid>
   <testCaseLink>
      <guid>7073145c-a9d1-4688-b2f0-13cfcbacb88c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Demo/DataSourceDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>39bc4af6-22bc-4c96-8d5c-742fb05bcdf1</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>39bc4af6-22bc-4c96-8d5c-742fb05bcdf1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>6871dee9-bc23-405b-ab8c-e025fd855ea7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>39bc4af6-22bc-4c96-8d5c-742fb05bcdf1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>a790cf13-e5af-43cd-b0b2-94ed264c67c7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
