<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_This username isnt available. Please try another</name>
   <tag></tag>
   <elementGuidId>8523d749-0d25-43f0-8506-48ca1b11e2d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='ssfErrorAlert']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ssfErrorAlert</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a92b4c6b-5440-4787-ac82-d0f3ad9a3b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>71522361-7540-4e0d-9c23-48c434646c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ssfErrorAlert</value>
      <webElementGuid>72c034f2-0618-4a8a-8efc-a6867c943892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>f2966650-b931-41ac-9850-4fdf626f8236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This username isn't available. Please try another.</value>
      <webElementGuid>caca604e-d03d-48c4-8d85-5d89bf4ef857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ssfErrorAlert&quot;)</value>
      <webElementGuid>d2b000b2-c52c-4c3b-990a-75c8e3b0bf91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='ssfErrorAlert']</value>
      <webElementGuid>3ad197d4-8d2d-4d64-8ea0-e67efad3bd13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mount_0_0_cM']/div/div/div[2]/div/div/div/div/section/main/div/div/div/div[2]/form/div[9]/p</value>
      <webElementGuid>accd9a3c-6d50-425d-86cb-6a61ce64d076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[1]/following::p[1]</value>
      <webElementGuid>81c3dcf4-f3ce-4d98-a279-ec8a36abb749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookies Policy'])[1]/following::p[1]</value>
      <webElementGuid>79021eaa-87b4-47fb-9029-9ae7a34a2def</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/preceding::p[1]</value>
      <webElementGuid>27af4582-58dd-480e-a0c6-8eaab7282287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get the app.'])[1]/preceding::p[2]</value>
      <webElementGuid>243f2c59-1473-4a94-9d05-8c341f6f420d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/p</value>
      <webElementGuid>c29ad031-3c32-42c1-b91b-71fa39c50f45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'ssfErrorAlert' and (text() = concat(&quot;This username isn&quot; , &quot;'&quot; , &quot;t available. Please try another.&quot;) or . = concat(&quot;This username isn&quot; , &quot;'&quot; , &quot;t available. Please try another.&quot;))]</value>
      <webElementGuid>d8eeba85-b61c-47a2-b0ec-df9cb95883d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
